import type { Metadata } from 'next'
import { Russo_One } from 'next/font/google'
import './globals.css'
import clsx from 'clsx'
import Providers from '@/providers'
import Header from '@/components/header'
import Footer from '@/components/footer'

const russo = Russo_One({ subsets: ['latin'], weight: ['400'] })

export const metadata: Metadata = {
  title: 'Battle Derby',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={clsx(
          russo.className,
          'min-h-screen bg-layer1 text-white flex flex-col bg-pattern bg-cover'
        )}
      >
        <Header />
        <main className="relative mx-auto my-4 max-w-7xl md:my-8 flex flex-col flex-1 gap-20">
          <Providers>{children}</Providers>
        </main>
        <Footer />
      </body>
    </html>
  )
}
